### ISSUE TITLE
Связать интерфейс получения execution events с сервером UnifiedViews

### ISSUE THREAD

**Issue by amivanoff** [agentlab/rdf-scheme-editor#137]
Связать интерфейс получения с execution events с сервером UnifiedViews

1. Связать интерфейс получения с сервером

2. Сделать JEST-тесты React компонента

Документация REST API https://help.poolparty.biz/pp7/developer-guide/semantic-integrator-apis/unifiedviews-apis/unifiedviews-api/unifiedviews-pipeline-execution-event-services/unifiedviews-method-request-all-pipeline-execution-events

Прототип интерфейса #90

Сам сервер где-то тут https://82.202.226.30:8080/

**Comment by amivanoff** [comment]
http://82.202.226.30:8080/unifiedviews
admin / test

**Comment by Trang5396** [comment]
от API не отвечает. Проверьте, пожалуйста! я не смогла связать с сервером от REST API.
![Снимок](https://user-images.githubusercontent.com/48272322/60337388-9f257400-99ab-11e9-9a5a-0105609bba05.JPG)
